runtime: nodejs20
service: backend-api

env_variables:
  MONGODB_URI: "mongodb+srv://niyomartin3:nn3ahPT6mfqJsh4W@cluster0.irjpwe3.mongodb.net/newgamedistribution?retryWrites=true&w=majority&appName=Cluster0"
  NODE_ENV: "production"

handlers:
  - url: /.*
    script: auto
    secure: optional